### ISSUE TITLE
module types are not downloaded recursively from imports

### ISSUE THREAD

**Issue by blcham** [YanDoroshenko/s-pipes-editor#4]
http://onto.fel.cvut.cz/ontologies/lib/sm-module-adapter imports http://topbraid.org/sparqlmotionlib-core, but module types from the imported ontology are absent.

**Comment by YanDoroshenko** [comment]
Resolved in [ce5ce88af563d2cf59f05ca0898a0ce7028a302d](https://github.com/YanDoroshenko/s-pipes-editor/commit/ce5ce88af563d2cf59f05ca0898a0ce7028a302d).
